# Generated by Django 3.2.3 on 2021-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bolum_baslama',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bolum_bitis',
            field=models.DateField(blank=True),
        ),
    ]
