# Generated by Django 3.2.3 on 2021-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210530_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bolum_baslama',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bolum_bitis',
            field=models.TextField(blank=True),
        ),
    ]
