# Generated by Django 3.2.3 on 2021-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210530_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, default='images/default_cover.png', null=True, upload_to='photos', verbose_name='profile cover'),
        ),
    ]
