# Generated by Django 3.2.3 on 2021-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, default='images/default_cover.gif', null=True, upload_to='photos', verbose_name='profile cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.jpg', null=True, upload_to='photos', verbose_name='profile photo'),
        ),
    ]
